### ISSUE TITLE
Eating from stack removes all with replace_with_item

### ISSUE THREAD

**Issue by tenplus1** [BlockMen/hud_hunger#14]
Eating from a stack of mushroom soup or hearty stew replaces the whole stack with a single bowl which isnt too good, so I've redone the routine within hunger.lua to add the replace_with_item to the inventory if space is available or drop as an item if not...

```
function hud.item_eat(hunger_change, replace_with_item, poisen, heal)
    return function(itemstack, user, pointed_thing)

        if itemstack:take_item() ~= nil and user ~= nil then

            local name = user:get_player_name()
            local h = tonumber(hud.hunger[name])
            local hp = user:get_hp()
            local rm = false
            local msg = nil

            -- Healing
            if hp < 20 and heal then
                hp = hp + heal
                if hp > 20 then hp = 20 end
                user:set_hp(hp)
                rm = true
                msg = ""
            elseif hp == 20 and heal then
                msg = "You already have full health"
            end

            -- Hunger
            if h < 30 and hunger_change then
                h = h + hunger_change
                if h > 30 then h = 30 end
                hud.hunger[name]=h
                hud.set_hunger(user)
                rm = true
            elseif h>= 30 and hunger_change and not msg then
                msg = "Cannot eat, not hungry"
            end

            if msg then minetest.chat_send_player(user:get_player_name(), msg) end

            -- Poison
            if poisen then
                poisenp(1.0, poisen, 0, user)
            end

            -- if item eaten and replace_with_item, check if inventory full, add/drop replacement
            if rm then
                local inv = user:get_inventory()
                if inv:room_for_item("main", {name=replace_with_item}) then
                    inv:add_item("main", replace_with_item)
                else
                    local pos = user:getpos()
                    pos.y = math.floor(pos.y + 0.5)
                    core.add_item(pos, replace_with_item)
                end

                return itemstack
            end

        end
    end
end
```

**Comment by p5yg3n** [comment]
I like this change but I think it should be fixed engine side too.

**Comment by 0-afflatus** [comment]
I agree with MT-Modder here, the behaviour of replace_with_item gives problems with my cauldron mod too.

**Comment by p5yg3n** [comment]
I submitted an issue here: https://github.com/minetest/minetest/issues/2292

**Comment by rubenwardy** [comment]
HUD should use minetest.register_on_item_eat to override the default eat action.

**Comment by p5yg3n** [comment]
I believe this is fixed by https://github.com/minetest/minetest/commit/efa977518a60c47f3c409449be202298900372e8?

**Comment by BlockMen** [comment]
@MT-Modder nope, since it not (yet) using minetest.item_eat()

**Comment by p5yg3n** [comment]
Oh...

**Comment by BlockMen** [comment]
Please open new issue if still present here: https://github.com/BlockMen/hunger
1071c7f13e491b2f3bc09bbbcb1bd6aaed6071c5
